# Generated by Django 4.2.17 on 2025-02-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_persona_bio_remove_persona_fotoperf_and_more'),
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estudios', to='persona.persona'),
        ),
    ]
