# Generated by Django 4.2.17 on 2025-02-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_titles'),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
