# Generated by Django 4.2.17 on 2025-02-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_titles'),
        ('titles', '0002_titles_persona_alter_titles_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Titles', to='persona.persona'),
        ),
    ]
