# Generated by Django 4.2.17 on 2025-02-09 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_persona_bio_remove_persona_fotoperf_and_more'),
        ('redsoc', '0002_redsoc_persona_alter_redsoc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsoc',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RedSoc', to='persona.persona'),
        ),
    ]
