# Generated by Django 4.2.17 on 2025-02-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0004_redsoc_iconoimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsoc',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='redsoc',
            name='telefono',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
