# Generated by Django 4.2.17 on 2025-02-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsoc', '0005_redsoc_email_redsoc_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redsoc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='redsoc',
            name='telefono',
        ),
    ]
