# Generated by Django 4.2.17 on 2025-06-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0006_persona_nacimiento_persona_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarImg', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('Persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecno', to='persona.persona')),
            ],
        ),
    ]
