# Generated by Django 4.2.17 on 2025-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologias',
            name='avatarImg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
