# Generated by Django 4.2.17 on 2025-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
