# Generated by Django 4.2.17 on 2025-02-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_foto_remove_post_title_post_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
    ]
