# Generated by Django 4.2.17 on 2025-02-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bio',
        ),
    ]
