# Generated by Django 4.2.17 on 2025-02-08 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_persona_bio_remove_persona_fotoperf_and_more'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajos',
            old_name='urlEmpresa',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='final',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='ocupacion',
        ),
        migrations.AddField(
            model_name='trabajos',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trabajos', to='persona.persona'),
        ),
        migrations.AddField(
            model_name='trabajos',
            name='urlTrabajo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='avatarImg',
            field=models.CharField(max_length=300),
        ),
    ]
