# Generated by Django 4.2.17 on 2025-02-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('persona', '0002_persona_bio_persona_fotoperf'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='titles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='titles.titles'),
        ),
    ]
