# Generated by Django 4.2.17 on 2025-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_persona_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='titles',
        ),
    ]
