# Generated by Django 4.2.17 on 2025-02-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fotoPerf',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='redes',
        ),
    ]
