# Generated by Django 4.2.17 on 2025-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_persona_bio_remove_persona_fotoperf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
