# Generated by Django 4.2.17 on 2024-12-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudios.estudios')),
                ('trabajos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajos')),
            ],
        ),
    ]
