# Generated by Django 4.2.17 on 2025-02-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='texto',
        ),
    ]
