# Generated by Django 4.2.17 on 2025-02-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_bio'),
        ('bio', '0003_remove_bio_estudios_remove_bio_trabajos_bio_fotoperf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='texto_dos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texto_dos', to='post.post'),
        ),
        migrations.AddField(
            model_name='bio',
            name='texto_uno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texto_uno', to='post.post'),
        ),
    ]
