# Generated by Django 4.2.17 on 2025-02-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_bio'),
        ('bio', '0004_bio_texto_dos_bio_texto_uno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='texto_dos',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='texto_uno',
        ),
        migrations.AddField(
            model_name='bio',
            name='textos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='post.post'),
        ),
    ]
