# Generated by Django 4.2.17 on 2025-02-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_bio'),
        ('bio', '0005_remove_bio_texto_dos_remove_bio_texto_uno_bio_textos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='textos',
        ),
        migrations.AddField(
            model_name='bio',
            name='textos',
            field=models.ManyToManyField(blank=True, null=True, related_name='textos', to='post.post'),
        ),
    ]
